name: Build Kivy APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Kivy funciona mejor con Python 3.8

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-dev \
            libffi-dev \
            libssl-dev \
            libxml2-dev \
            libxslt1-dev \
            libjpeg-dev \
            zlib1g-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev

    - name: Create and activate virtualenv
      run: |
        python -m pip install --upgrade pip virtualenv
        python -m virtualenv venv
        source venv/bin/activate

    - name: Install core dependencies first
      run: |
        source venv/bin/activate
        pip install --no-deps cython==0.29.36
        pip install wheel setuptools
        pip install kivy==2.1.0

    - name: Install remaining dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt --use-pep517
