name: Build Kivy APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-dev \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            libjpeg-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libopenal-dev \
            libgstreamer1.0-dev

    - name: Set up virtual environment
      run: |
        python -m pip install --upgrade pip==23.1.2 virtualenv==20.24.2
        python -m virtualenv venv
        source venv/bin/activate

    - name: Install core packages first
      run: |
        source venv/bin/activate
        pip install --no-cache-dir cython==0.29.36
        pip install --no-cache-dir setuptools==65.5.0 wheel==0.38.4
        pip install --no-cache-dir kivy==2.1.0

    - name: Install requirements with retry
      run: |
        source venv/bin/activate
        for i in {1..3}; do
          pip install --no-cache-dir -r requirements.txt && break
          echo "Intento $i fallido, reintentando..."
          sleep 5
        done
