name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          git clone https://github.com/kivy/python-for-android
          cd python-for-android
          ./distribute.sh -m "kivy" -d TouchMe
      - name: Build APK
        run: |
          cd python-for-android/TouchMe
          ./build.py --dir $GITHUB_WORKSPACE --package org.touchme --name "TouchMe"
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TouchMe-APK
          path: python-for-android/TouchMe/bin/
