name: Build Kivy APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Versión más estable para Kivy

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            git \
            openjdk-11-jdk \
            zlib1g-dev \
            libncurses5-dev \
            libssl-dev \
            libffi-dev \
            python3-pip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libltdl-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install virtualenv
        python -m virtualenv venv
        source venv/bin/activate
        pip install kivy==2.1.0  # Versión conocida como estable
        pip install buildozer
        pip install -r requirements.txt

    - name: Initialize Buildozer
      run: |
        source venv/bin/activate
        buildozer init
        # Configuración mínima requerida
        echo "[app]" > buildozer.spec
        echo "title = MyApp" >> buildozer.spec
        echo "package.name = myapp" >> buildozer.spec
        echo "package.domain = org.test" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,atlas" >> buildozer.spec
        echo "version = 1.0" >> buildozer.spec
        echo "requirements = python3,kivy==2.1.0" >> buildozer.spec
        echo "android.permissions = INTERNET" >> buildozer.spec
        echo "android.api = 30" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec
        echo "android.ndk = 23b" >> buildozer.spec

    - name: Build APK with Buildozer
      run: |
        source venv/bin/activate
        buildozer -v android debug
        ls -la bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-APK
        path: bin/*.apk
